const ENV = import.meta.env;

export const REACT_APP_API_URL = ENV.VITE_API_URL;
export const PUBLIC_REDIRECT_URI = ENV.VITE_REDIRECT_URI;

export const PUBLIC_KAKAO_CLIENT_ID = ENV.VITE_KAKAO_CLIENT_ID;
export const PUBLIC_GOOGLE_CLIENT_ID = ENV.VITE_GOOGLE_CLIENT_ID;
export const PUBLIC_GOOGLE_CLIENT_SECRET = ENV.VITE_GOOGLE_CLIENT_SECRET;

export const TEST_REDIRECT_URI = ENV.VITE_TEST_REDIRECT_URI;
export const TEST_GOOGLE_REDIRECT_URI = ENV.VITE_TEST_GOOGLE_REDIRECT_URI;
