const ENV = import.meta.env;

export const REACT_APP_API_URL = ENV.VITE_API_URL;
export const PUBLIC_KAKAO_CLIENT_ID = ENV.VITE_PUBLIC_KAKAO_CLIENT_ID;
export const PUBLIC_REDIRECT_URI = ENV.VITE_PUBLIC_REDIRECT_URI;

export const TEST_REDIRECT_URI = ENV.VITE_TEST_REDIRECT_URI;
