const ENV = import.meta.env;

export const REACT_APP_API_URL = ENV.VITE_API_URL;

export const PUBLIC_KAKAO_CLIENT_ID = ENV.VITE_KAKAO_CLIENT_ID;
export const KAKAO_REDIRECT_URI = ENV.VITE_KAKAO_REDIRECT_URI;

export const PUBLIC_GOOGLE_CLIENT_ID = ENV.VITE_GOOGLE_CLIENT_ID;
export const PUBLIC_GOOGLE_CLIENT_SECRET = ENV.VITE_GOOGLE_CLIENT_SECRET;
export const GOOGLE_REDIRECT_URI = ENV.VITE_GOOGLE_REDIRECT_URI;

export const PUBLIC_NAVER_CLIENT_ID = ENV.VITE_NAVER_CLIENT_ID;
export const PUBLIC_NAVER_CLIENT_SECRET = ENV.VITE_NAVER_CLIENT_SECRET;
export const NAVER_REDIRECT_URI = ENV.VITE_NAVER_REDIRECT_URI;
